### ISSUE TITLE
Rotate screen

### ISSUE THREAD

**Issue by scott1423** [afiskon/stm32-st7735#1]
Hi
 I am testing the CubeMX demo, and works well. As I am writing in C for the STM32 I am finding it difficult to rotate the screen, I would like to change to landscape mode, can anyone help please. Also is the a C version of the library?

Many Thanks
Scott

**Comment by afiskon** [comment]
Hello @scott1423 

You can change the screen orientation by editing ST7735_ROTATION macro, see examples in https://github.com/afiskon/stm32-st7735/blob/master/st7735/st7735.h

The library is written in C.

**Comment by scott1423** [comment]
Hi 
  Many thanks for your reply.  I see the line #define ST7735_ROTATION (ST7735_MADCTL_MY | ST7735_MADCTL_MV)  but where do I use this?  

Best Regards
Scott

**Comment by afiskon** [comment]
You can redefine it right in the file or comment the line and use compiler flags instead.
