### ISSUE TITLE
what function i need use for print in st7735 adc or any int16_t value?

### ISSUE THREAD

**Issue by marenko21** [afiskon/stm32-st7735#7]
hi,it is necessary to display the  ADC value or any int16_t digit value by what function it can be done,i dont find it in library if i use

int16_t adc ;
//for example adc=120;
ST7735_WriteString(0,160,adc,Font_16x26,WHITE,BLACK);
or
ST7735_WriteChar(0,160,adc,Font_16x26,WHITE,BLACK);
its dont work,show only not correct characters

help me please,thanks.

**Comment by afiskon** [comment]
@marenko21 ,

Use snprintf() to convert a number to a string, and then display a string. Here is a complete example for ADC https://eax.me/stm32-multi-channel-adc/

Feel free to re-open the issue if you will have any other problems with the library.

**Comment by marenko21** [comment]
Great thanks!, all work how i need.
